version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-cbwebsite-messenger"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tqxx7685bpf7"
s3_prefix = "sam-cbwebsite-messenger"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
