AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-cbwebsite-messenger

  Sample SAM Template for sam-cbwebsite-messenger

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - stage
      - main
      - test
      - develop
    Default: develop
    Description: State that can be added to resource names

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 25
    Runtime: python3.8
    Environment:
      Variables:
        TOPIC_ARN: arn:aws:sns:ap-southeast-1:428846808097:CbwebsiteMessenger
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'*'"

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: CBMessenger
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
      StageName: !Ref Environment

  CbWebsiteMessengerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cbwebsite-messenger/
      Handler: app.lambda_handler
      Events:
        CbWebsiteMessenger:
          Type: Api
          Properties:
            Path: /contact
            Method: post
            RestApiId: !Ref RestApi

Outputs:
  CbWebsiteMessengerApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com"
